HospitalUI/Controllers/ProjectStatusController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HospitalUI.Controllers
{
    public class ProjectStatusController : Controller
    {
        // GET: ProjectStatus
        ProjectStatusManager psm = new ProjectStatusManager(new ProjectStatusDal());
        [Authorize]
        public ActionResult Index()
        {
            var x = psm.GetList().Where(a => a.ProjeStatus == true).ToList();
            return View(x);
        }
        [HttpGet]
        public ActionResult AddProjectStatus()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddProjectStatus(ProjectStatus procetStatus)
        {
            procetStatus.ProjeStatus = true;
            psm.ProjectStatuseAdd(procetStatus);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult UpdateProjectStatus(int id)
        {
            var x = psm.GetById(id);
            return View(x);
        }
        [HttpPost]
        public ActionResult UpdateProjectStatus(ProjectStatus projectStatus)
        {
            psm.ProjectStatusUpdate(projectStatus);
            return RedirectToAction("Index");
        }

        public ActionResult DeleteProjectStatus(int id)
        {
            var x = psm.GetById(id);
            x.ProjeStatus = false;
            psm.ProjectStatuseDelete(x);
            return RedirectToAction("Index");
        }
    }
}

HospitalUI/Views/ProjectStatus/AddProjectStatus.cshtml
@model EntityLayer.Concrete.ProjectStatus
@{
    ViewBag.Title = "AddProjectStatus";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

@using (Html.BeginForm("AddProjectStatus", "ProjectStatus", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Proje Durumu")
        @Html.TextBoxFor(x => x.ProStatus, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.ProStatus)
        <button class="btn btn-info">Kaydet</button>

    </div>
}

HospitalUI/Views/ProjectStatus/Index.cshtml
@using EntityLayer.Concrete
@model List<ProjectStatus>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h3>Durum Sayfası</h3>
<br />
<!DOCTYPE html>
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

<table class="table table-hover">
    <tr>
        <th>ID</th>
        <th>Proje Durumu</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.StatusId</td>
            <td>@item.ProStatus</td>
            <td><a href="/ProjectStatus/DeleteProjectStatus/@item.StatusId" class="btn btn-danger">SİL</a></td>
            <td><a href="/ProjectStatus/UpdateProjectStatus/@item.StatusId" class="btn btn-warning">GÜNCELLE</a></td>
        </tr>
    }
</table>
<a href="/ProjectStatus/AddProjectStatus" class="btn btn-info">Yeni Proje Durumu Girişi</a>

HospitalUI/Views/ProjectStatus/UpdateProjectStatus.cshtml
@model  EntityLayer.Concrete.ProjectStatus
@{
    ViewBag.Title = "UpdateProjectStatus";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

@using (Html.BeginForm("UpdateProjectStatus", "ProjectStatus", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("ID")
        @Html.TextBoxFor(x => x.StatusId, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.StatusId)
        <br />
        @Html.Label("Tüp Cinsi")
        @Html.TextBoxFor(x => x.ProStatus, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.ProStatus)
        <br /><br />
        <button class="btn btn-success">GÜNCELLE</button>

    </div>
}