HospitalUI/Controllers/ProjectTypeController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HospitalUI.Controllers
{
    public class ProjectTypeController : Controller
    {
        // GET: ProjectType
        ProjectTypeManager ptm = new ProjectTypeManager(new ProjectTypeDal());
        [Authorize]
        public ActionResult Index()
        {
            var x = ptm.GetList().Where(a => a.TypeStatus == true).ToList();
            return View(x);
        }
        [HttpGet]
        public ActionResult AddProjectType()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddProjectType(ProjectType projectType)
        {
            projectType.TypeStatus = true;
            ptm.ProjectTypeAdd(projectType);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult UpdateProjectType(int id)
        {
           var x= ptm.GetById(id);
            return View(x);
        }
        [HttpPost]
        public ActionResult UpdateProjectType(ProjectType projectType)
        {
            ptm.ProjectTypeUpdate(projectType);
            return RedirectToAction("Index");
        }

        public ActionResult DeleteProjectType(int id)
        {
            var x = ptm.GetById(id);
            x.TypeStatus = false;
            ptm.ProjectTypeDelete(x);
            return RedirectToAction("Index");
        }
    }
}

HospitalUI/Views/ProjectType/AddProjectType.cshtml
@model EntityLayer.Concrete.ProjectType 
@{
    ViewBag.Title = "AddProjectType";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

@using (Html.BeginForm("AddProjectType", "ProjectType", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Proje Türü")
        @Html.TextBoxFor(x => x.ProType, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.ProType)
        <button class="btn btn-info">Kaydet</button>

    </div>
}

HospitalUI/Views/ProjectType/Index.cshtml
@using EntityLayer.Concrete
@model List<ProjectType>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<h3>Proje Türü Sayfası</h3>
<br />
<!DOCTYPE html>
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

<table class="table table-hover">
    <tr>
        <th>ID</th>
        <th>Proje Türü</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.ProjectTypeId</td>
            <td>@item.ProType</td>
            <td><a href="/ProjectType/DeleteProjectType/@item.ProjectTypeId" class="btn btn-danger">SİL</a></td>
            <td><a href="/ProjectType/UpdateProjectType/@item.ProjectTypeId" class="btn btn-warning">GÜNCELLE</a></td>
        </tr>
    }
</table>
<a href="/ProjectType/AddProjectType" class="btn btn-info">Yeni Proje Türü Girişi</a>

HospitalUI/Views/ProjectType/UpdateProjectType.cshtml
@model EntityLayer.Concrete.ProjectType
@{
    ViewBag.Title = "UpdateProjectType";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

@using (Html.BeginForm("UpdateProjectType", "ProjectType", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("ID")
        @Html.TextBoxFor(x => x.ProjectTypeId, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.ProjectTypeId)
        <br />
        @Html.Label("Tüp Cinsi")
        @Html.TextBoxFor(x => x.ProType, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.ProType)
        <br /><br />
        <button class="btn btn-success">GÜNCELLE</button>

    </div>
}