HospitalUI/Controllers/TypeOfCancerController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HospitalUI.Controllers
{
    public class TypeOfCancerController : Controller
    {
        // GET: TypesOfCancer
        TypeOfCancerManager tm = new TypeOfCancerManager(new TypeOfCancerDal());
        [Authorize]
        public ActionResult Index()
        {
            var x = tm.GetList().Where(a => a.CancerStatus == true).ToList();
            return View(x);
        }
        [HttpGet]
        public ActionResult AddTypeOfCancer()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddTypeOfCancer(TypesOfCancer t)
        {
            t.CancerStatus = true;
            tm.TypesOfCancerAdd(t);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult UpdateTypeOfCancer(int id)
        {
           var x= tm.GetById(id);
            return View(x);
        }
        [HttpPost]
        public ActionResult UpdateTypeOfCancer(TypesOfCancer t)
        {
            tm.TypeOfCancerUpdate(t);
            return RedirectToAction("Index");
        }
        public ActionResult DeleteTypeOfCancer(int id)
        {
            var x = tm.GetById(id);
            x.CancerStatus = false;
            tm.TypeOfCancerDelete(x);
            return RedirectToAction("Index");
        }
    }
}

HospitalUI/Views/TypeOfCancer/AddTypeOfCancer.cshtml
@model EntityLayer.Concrete.TypesOfCancer
@{
    ViewBag.Title = "AddTypeOfCancer";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

@using (Html.BeginForm("AddTypeOfCancer", "TypeOfCancer", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Kanser Türü")
        @Html.TextBoxFor(x => x.CancerName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CancerName)
        <button class="btn btn-info">Kaydet</button>

    </div>
}

HospitalUI/Views/TypeOfCancer/Index.cshtml
@using EntityLayer.Concrete
@model List<TypesOfCancer>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h3>Kanser Türleri Sayfası</h3>
<br />
<!DOCTYPE html>
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

<table class="table table-hover">
    <tr>
        <th>ID</th>
        <th>Kanser Adı</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.CancerId</td>
            <td>@item.CancerName</td>
            <td><a href="/TypeOfCancer/DeleteTypeOfCancer/@item.CancerId" class="btn btn-danger">SİL</a></td>
            <td><a href="/TypeOfCancer/UpdateTypeOfCancer/@item.CancerId" class="btn btn-warning">GÜNCELLE</a></td>
        </tr>
    }
</table>
<a href="/TypeOfCancer/AddTypeOfCancer" class="btn btn-info">Yeni Kanser Türü Girişi</a>

HospitalUI/Views/TypeOfCancer/UpdateTypeOfCancer.cshtml
@model EntityLayer.Concrete.TypesOfCancer
@{
    ViewBag.Title = "UpdateTypeOfCancer";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

@using (Html.BeginForm("UpdateTypeOfCancer", "TypeOfCancer", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("ID")
        @Html.TextBoxFor(x => x.CancerId, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CancerId)
        <br />
        @Html.Label("Kanser türü")
        @Html.TextBoxFor(x => x.CancerName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CancerName)
        <br /><br />
        <button class="btn btn-success">GÜNCELLE</button>

    </div>
}